sample_timeout: 20
debug: False
api_url: '$TESTING_API_URL'
access_token: '$AUTH_TOKEN'
substitutions:
  '{version}': 'v1'
  '<ACCESS_TOKEN>': '$AUTH_TOKEN'
  'api-sandbox.oftrust.net': '$TESTING_API_URL'

resp_attr_replacements:
  'product-api/products/{version}':
    - 'productCode': 'product_code'
  'message-api/messages/v1':
    - '@id': 'id'
  'calendar-api/calendars/v1':
    - '@id': 'id'
  'identity-api/identities/v1':
    - '@id': 'id'
  'identity-api/identities/v1/{from_identity}/link/{to_identity}':
    - '@type': 'type'
  'identity-api/identities/v1/{from_identity}/link/{to_identity}/{type}':
    - '@type': 'type'

before_sample:
  'message-api/messages/v1':
    - resource: 'Identity'
      method: 'POST'
      subs:
        '@id': '0920a84a-1548-4644-b95d-e3f80e1b9ca6'
  'calendar-api/calendars/v1':
    - resource: 'Identity'
      method: 'POST'
      subs:
        '@id': '0920a84a-1548-4644-b95d-e3f80e1b9ca6'
  'identity-api/identities/v1/{from_identity}/link/{to_identity}':
    - resource: 'Identity'
      method: 'POST'
      subs:
        '@id': '{to_identity}'
    - resource: 'Identity'
      method: 'POST'
      subs:
        '@id': '{from_identity}'
  'identity-api/identities/v1/dataDiscovery':
    - resource: 'Identity'
      method: 'GET'
      subs:
        '@id': 'fc3bced4-a132-4293-9240-4d0f02277e2e'
  'identity-api/identities/v1/discovery':
    - resource: 'Identity'
      method: 'GET'
      subs:
        '@id': 'fc3bced4-a132-4293-9240-4d0f02277e2e'
  'acl-api/acl/v1/{from_identity}/{target_identity}':
    - resource: 'Identity'
      method: 'POST'
      subs:
        '@id': '{from_identity}'
    - resource: 'Identity'
      method: 'POST'
      subs:
        '@id': '{target_identity}'
  'product-api/products/{version}':
    - resource: 'DeleteProduct'
      method: 'POST'
      subs: {}
  'application-api/apps/v1':
    - resource: 'Identity'
      method: 'POST'
      subs:
        '@id': 'bfec43ac-a0ce-4469-a78f-3106cf28b4c9'

ignore_failures:
  'broker-api/broker/{version}/fetch-data-product':
    - 'POST'
  'product-api/products/{version}/{product_code}':
    - 'DELETE'